# Generated by Django 2.2.4 on 2019-10-03 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_eveonline_connector', '0005_auto_20191003_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveJournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('first_party', models.CharField(max_length=128)),
                ('first_party_type', models.CharField(choices=[('CHARACTER', 'CHARACTER'), ('CORPORATION', 'CORPORATION')], max_length=32)),
                ('second_party', models.CharField(max_length=128)),
                ('second_party_type', models.CharField(choices=[('CHARACTER', 'CHARACTER'), ('CORPORATION', 'CORPORATION')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EveTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('item', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('is_buy', models.BooleanField()),
                ('client_id', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='django_eveonline_connector.EveEntity')),
            ],
        ),
        migrations.CreateModel(
            name='EveSkillPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skillpoints', to='django_eveonline_connector.EveEntity')),
            ],
        ),
        migrations.CreateModel(
            name='EveNetWorth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth', to='django_eveonline_connector.EveEntity')),
            ],
        ),
        migrations.CreateModel(
            name='EveContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('issued_by', models.CharField(max_length=128)),
                ('issued_to', models.CharField(max_length=128)),
                ('issued_by_type', models.CharField(choices=[('CHARACTER', 'CHARACTER'), ('CORPORATION', 'CORPORATION')], max_length=32)),
                ('issued_to_type', models.CharField(choices=[('CHARACTER', 'CHARACTER'), ('CORPORATION', 'CORPORATION')], max_length=32, null=True)),
                ('accepted_by', models.CharField(max_length=128, null=True)),
                ('accepted_by_type', models.CharField(choices=[('CHARACTER', 'CHARACTER'), ('CORPORATION', 'CORPORATION')], max_length=32, null=True)),
                ('contract_type', models.CharField(max_length=32)),
                ('contract_status', models.CharField(max_length=64)),
                ('contract_value', models.FloatField()),
                ('contract_items', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='django_eveonline_connector.EveEntity')),
            ],
        ),
        migrations.CreateModel(
            name='EveContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_type', models.CharField(choices=[('CHARACTER', 'CHARACTER'), ('CORPORATION', 'CORPORATION'), ('ALLIANCE', 'ALLIANCE')], max_length=32)),
                ('standing', models.FloatField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='django_eveonline_connector.EveEntity')),
            ],
        ),
        migrations.CreateModel(
            name='EveClone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('implants', models.TextField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clones', to='django_eveonline_connector.EveEntity')),
            ],
        ),
        migrations.CreateModel(
            name='EveAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('item_type', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='django_eveonline_connector.EveEntity')),
            ],
        ),
        migrations.CreateModel(
            name='EveSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='django_eveonline_connector.EveEntity')),
            ],
            options={
                'unique_together': {('entity', 'name')},
            },
        ),
    ]
