# Generated by Django 2.2.4 on 2019-10-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecontract',
            name='issued_to',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
