# Generated by Django 2.2.4 on 2019-10-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0002_auto_20191004_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveskill',
            name='group',
            field=models.CharField(default='Test', max_length=64),
            preserve_default=False,
        ),
    ]
