# Generated by Django 2.2.4 on 2019-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0004_auto_20191005_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='evejournalentry',
            name='external_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
