# Generated by Django 2.2.4 on 2019-10-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_connector', '0006_auto_20191003_2008'),
        ('django_eveonline_entity_extensions', '0005_evejournalentry_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evejournalentry',
            name='entity',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='django_eveonline_connector.EveEntity'),
            preserve_default=False,
        ),
    ]
