# Generated by Django 2.2.4 on 2019-10-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0006_evejournalentry_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evejournalentry',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='django_eveonline_connector.EveEntity'),
        ),
    ]
