# Generated by Django 2.2.4 on 2019-10-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0008_evejournalentry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evetransaction',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='evetransaction',
            name='value',
        ),
        migrations.AddField(
            model_name='evetransaction',
            name='journal_entry',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_eveonline_entity_extensions.EveJournalEntry'),
            preserve_default=False,
        ),
    ]
