# Generated by Django 2.2.4 on 2019-10-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0009_auto_20191023_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='evetransaction',
            name='external_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
