# Generated by Django 2.2.4 on 2019-10-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0010_evetransaction_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evetransaction',
            name='journal_entry',
        ),
        migrations.AddField(
            model_name='evetransaction',
            name='client',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evetransaction',
            name='client_type',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
