# Generated by Django 2.2.4 on 2019-10-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0011_auto_20191023_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='evetransaction',
            name='client_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
