# Generated by Django 2.2.4 on 2019-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0012_evetransaction_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evetransaction',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
