# Generated by Django 2.2.8 on 2019-12-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0013_evetransaction_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenetworth',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='eveskillpoints',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
