# Generated by Django 2.2.8 on 2019-12-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0014_auto_20191212_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecontract',
            name='external_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='evejournalentry',
            name='external_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='evetransaction',
            name='external_id',
            field=models.BigIntegerField(),
        ),
    ]
