# Generated by Django 2.2.8 on 2019-12-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_entity_extensions', '0015_auto_20191216_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveasset',
            name='item',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='evetransaction',
            name='item',
            field=models.CharField(max_length=128),
        ),
    ]
